/**
 * Generates JSON Schema files for every job contract in @jmos/core into the Python worker
 * package. The zod definitions stay the single source of truth.
 *
 *   pnpm contracts:generate   write the files
 *   pnpm contracts:check      fail if the committed files are stale (runs in `pnpm verify`)
 */
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { z } from 'zod';
import { jobContractKey, jobContracts } from '../packages/core/src/index';

const OUTPUT_DIR = resolve(
  import.meta.dirname,
  '../apps/ai-worker/src/jmos_worker/contract_schemas',
);
const check = process.argv.includes('--check');

function render(): Map<string, string> {
  const files = new Map<string, string>();
  for (const contract of jobContracts) {
    const document = {
      $comment: 'GENERATED by `pnpm contracts:generate` from packages/core. Do not edit.',
      type: contract.type,
      schema_version: contract.schemaVersion,
      description: contract.description,
      input: z.toJSONSchema(contract.input, { target: 'draft-2020-12' }),
      output: z.toJSONSchema(contract.output, { target: 'draft-2020-12' }),
    };
    files.set(`${jobContractKey(contract)}.json`, `${JSON.stringify(document, null, 2)}\n`);
  }
  return files;
}

async function main(): Promise<void> {
  const expected = render();
  await mkdir(OUTPUT_DIR, { recursive: true });
  const existing = (await readdir(OUTPUT_DIR)).filter((name) => name.endsWith('.json'));

  if (check) {
    const problems: string[] = [];
    for (const [name, content] of expected) {
      const current = existing.includes(name)
        ? await readFile(join(OUTPUT_DIR, name), 'utf8')
        : null;
      if (current === null) problems.push(`missing ${name}`);
      else if (current.replace(/\r\n/g, '\n') !== content) problems.push(`stale ${name}`);
    }
    for (const name of existing) {
      if (!expected.has(name)) problems.push(`orphaned ${name}`);
    }
    if (problems.length > 0) {
      console.error(`Job contract JSON Schemas are out of date:\n  ${problems.join('\n  ')}`);
      console.error('Run `pnpm contracts:generate` and commit the result.');
      process.exit(1);
    }
    console.log(`contracts: ${String(expected.size)} job contract schema(s) up to date`);
    return;
  }

  for (const name of existing) {
    if (!expected.has(name)) await rm(join(OUTPUT_DIR, name));
  }
  for (const [name, content] of expected) {
    await writeFile(join(OUTPUT_DIR, name), content, 'utf8');
  }
  console.log(`contracts: wrote ${String(expected.size)} schema(s) to ${OUTPUT_DIR}`);
}

await main();
